server:
  port: 9100

spring:
  datasource:
    initialization-mode: always #启动时初始化数据库
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33698/blog_mybatis_thymeleaf?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      use-global-data-source-stat: true
      filters: stat #配置Druid监控的Filter,这样才能监控到sql语句
      stat-view-servlet: # 配置监控服务器
        enabled: true
        login-username: admin
        login-password: pxz20000305
        reset-enable: true
        url-pattern: /druid/*
        allow: 127.0.0.1 # ip白名单
      web-stat-filter:
        enabled: true
        session-stat-enable: true
        url-pattern: /*  # 添加过滤规则
        exclusions: "*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,/druid/*"  # 忽略过滤格式
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
logging:
  level:
    root: error
    org.springframework.boot.autoconfigure: error
    com.buffll: error

mybatis:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰
    cache-enabled: true #开启二级缓存

# 文件上传路径:
firstPicture.dir: /usr/local/static/upload/FirstPicture/

# 图片所在的文件夹(删除时要用)
imgPath: /usr/local/static/